Feat: Feat: 나이별/성별별 통계 추가 - 김현수
4th-wanted-pre-onboarding-teamD/user-community-service pull request #16
Opened 2022-09-05 06:20 UTC by HyeonsooKim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정
- [ ] 문서 작업

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 나이별 / 성별별 통계
 - user 나이별/성별별 통계 
 - login log 기준 나이별/성별별 통계 
 - 각 게시판 나이별/성별별 통계

2022-09-05 09:12 UTC, Hyes-y requested changes
확인했습니다! settings.py conflict만 해결해주시면 될 것 같습니다!

2022-09-05 09:14 UTC, BomiChoi approved these changes
확인했습니다!

2022-09-05 14:09 UTC, nicholas019 commented
![스크린샷 2022-09-05 오후 11 09 34](https://user-images.githubusercontent.com/103249222/188468050-9c02b3a6-c79d-432f-8cbe-cc258909c243.png)

요기 컴플릿트만 해결하면 될거같습니다

2022-09-06 00:35 UTC, nicholas019 approved these changes
확인했습니다

2022-09-06 00:39 UTC, merged